---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  
  - name: Debug Instance Info
    debug: 
      var: result

  - name: Delete instance "{{ result.openstack_servers.name }}"
    os_server:
      cloud: ospcloud
      name: "{{ result.openstack_servers.name }}"
      state: absent
