---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  
  - name: Debug Instance Info
    debug: 
      var: result

  - name: Delete instance "{{ result['openstack_servers']['instance_name'] }}"
    os_server:
      cloud: ospcloud
      name: "{{ item['public_v4'] }}"
      state: absent
    with_items: "{{ result['ansible_facts']['openstack_servers'] }}"

