---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  
  - name: Debug Instance Info
    debug: 
      var: result

  - name: Delete instance "{{ item['instance_name'] }}"
    os_server:
      cloud: ospcloud
      name: "{{ item['instance_name'] }}"
      state: absent
    loop: "{{ result['openstack_servers'] }}"
