---
- name: Check AWS servers with a simple smoke test
  hosts: localhost
  gather_facts: false
  vars_files:
    - env_guids.yml
  tasks:

  - name: Create In-memory Inventory
    add_host:
      name: workstation-{{OSP_GUID}}.rhpds.opentlc.com
      group: workstation
      ansible_ssh_private_key_file: /root/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
 
- name: Get AWS Servers info from In-memory Inventory
  hosts: workstation
  gather_facts: false
  # become: yes
  # remote_user: root
  vars_files:
    - env_guids.yml
  tasks:
 
  - name: OpenStack servers
    os_server_info:
      cloud: ospcloud
      server: 'frontend'
    register: openstack_info
    tags:
      - lbs
      - haproxy

  - name: Show info from AWS frontend servers
    debug:
      var: openstack_info

  - name: Curl website on frontend AWS instance for smoke test
    uri:
      url: http://frontend.{{TIER_GUID}}.example.opentlc.com
      return_content: yes
    register: awspage
    failed_when: "'Ansible has done its job' not in awspage.content"
    tags:
      - lbs
      - haproxy

