- hosts: frontends
  gather_facts: false
  tasks:

  - name: Get info from AWS servers
    os_server_info:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - aws.smoke

  - name: Show info from AWS servers
    debug:
      var: openstack_info

  - name: Curl website on frontend AWS instance for smoke test
    uri:
      url: http://{{ item['public_v4'] }}/index.html
      return_content: yes
    loop: "{{ openstack_info['openstack_servers'] }}"
    register: awspage
    tags:
      - aws.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: 'Ansible has done its job' not in "{{ awspage['content'] }}"
    tags:
      - aws.smoke
