---
- name: Check AWS servers with a simple smoke test
  hosts: localhost
  gather_facts: false
  vars_files:
    - env_guids.yml
  tasks:

  - name: Create In-memory Inventory
    add_host:
      name: workstation-{{OSP_GUID}}.rhpds.opentlc.com
      group: workstation
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user


- name: Get AWS Servers info from In-memory Inventory
  hosts: workstation
  gather_facts: false
  vars_files:
    - env_guids.yml
  tasks:

  - name: OpenStack servers
    os_server_info:
      cloud: ospcloud
      server: 'frontend'
    register: openstack_info
    tags:
      - lbs
      - haproxy

  - name: Show info from AWS servers
    debug:
      var: openstack_info

  - name: Curl website on frontend AWS instance for smoke test
    uri:
      ###  url: http://{{ item['public_v4'] }}/index.html
      url: http://frontend.{{TIER_GUID}}.example.opentlc.com
      return_content: yes
    loop: "{{ openstack_info['openstack_servers'] }}"
    register: awspage
    tags:
      - lbs
      - haproxy

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in {{ awspage['content'] }}"
