---
- name: Check AWS servers with a simple smoke test
  hosts: localhost
  gather_facts: false
  vars_files:
    - env_guids.yml
  tasks:

  - name: Curl website on frontend AWS instance for smoke test
    uri:
      url: http://frontend.{{TIER_GUID}}.example.opentlc.com
      return_content: yes
    register: awspage
    failed_when: "'Ansible has done its job' not in awspage.content"

