---
# tasks file for osp-smoke-test- hosts: workstation
  gather_facts: false
  tasks:

  - name: Get info from OpenStack servers
    os_server_info:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: Show info from Openstack servers
    debug:
      var: openstack_info

  - name: Curl website on frontend OSP instance
    uri:
      url: http://frontend.{{ GUID }}.example.opentlc.com/index.html
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
