---

# tasks file for osp.servers
  - name: Create new server instances and attaches them a network and passes metadata to the instance
    os_server:
      cloud: ospcloud
      name: "{{ item['value']['instance_name'] }}"
      image: rhel-guest
      meta: "group={{ item['value']['group'] }},deployment_name={{ item['value']['deployment'] }}"
      flavor: m2.small
      security_groups: "{{ item['value']['security_group_name'] }}"
      key_name: ansible_ssh
      wait: yes
      nics:
      - net-name: int_network
      userdata: |
        #!/bin/bash
        curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
        cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
        curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
        cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
    register: instanceip
    with_dict: "{{ osp_servers }}"

  - name: Add floating IP to instance
    os_floating_ip:
      cloud: ospcloud
      state: present
      reuse: yes
      server: "{{ item['value']['instance_name'] }}"
      network: ext_network
      wait: true
      timeout: 120
    register: instancefloatingip
    with_dict: "{{ osp_servers }}"

  - name: Show var collected on previows playbook
    debug:
      var: instancefloatingip['results']

  - name: Show instance public IP
    debug:
      var: "{{ item['floating_ip']['floating_ip_address'] }}"
    loop: "{{ instancefloatingip['results'] }}" 
 
  - name: Wait for 5 minutes until instance to be available
    wait_for:
      host: "{{ item['floating_ip']['floating_ip_address'] }}" 
      port: 22
      connect_timeout: 600
      search_regex: OpenSSH
      timeout: 600
    delegate_to: "{{ inventory_hostname }}"
    loop: "{{ instancefloatingip['results'] }}" 
