---
# tasks file for roles/osp-instance-start
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  
  - name: Debug Instance Info
    debug: 
      var: result

  - name: Start instance if it exists avoiding next playbooks timeouts
    os_server_action:
      cloud: ospcloud
      server: "{{ item['id'] }}"
      action: start
    loop: "{{ result['openstack_servers'] }}"
